export { GrDeliver } from "react-icons/gr";
export { FaLocationDot } from "react-icons/fa6";
export { FaArrowRight } from "react-icons/fa";
export { IoMdInformationCircleOutline } from "react-icons/io";
export { HiOutlineBuildingStorefront } from "react-icons/hi2";
export { FaAngleDown } from "react-icons/fa6";
export { IoMdCheckmarkCircleOutline } from "react-icons/io";
export {  TbBasketPlus } from "react-icons/tb";
export { IoIosArrowForward } from "react-icons/io";
